server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Sept-24?createDatabaseIfNotExist=true
    username: root
    password:  Pavan@2010
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true